spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wsuchat

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/wsu
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  profiles:
    active: local

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
test:
  project:
    topic: dev-topic
